Fix products routes
lizrag/SweetWorld pull request #2
Opened 2022-06-07 00:09 UTC by lizrag

Fix product routes, instance on product controller and add product routes on the index.

2022-06-07 22:40 UTC, oscarvajalmora requested changes

2022-06-07 22:40 UTC, oscarvajalmora commented on controllers/product.controller.js
> +export default new ProductController;
La instancia debiese ser `new ProductController();`

2022-06-07 22:52 UTC, lizrag commented on controllers/product.controller.js
> +export default new ProductController;
Done

2022-06-08 00:30 UTC, oscarvajalmora commented on controllers/product.controller.js
> +  createProduct = (req, res,) => {};
Por alguna razón prettier no pasó por estas funciones. Fíjate que algunos tienen la coma al final y otros no. No es algo bloqueante pero para que le pongas un ojo a esos detalles.

2022-06-08 00:31 UTC, oscarvajalmora approved these changes

2022-06-08 00:38 UTC, merged